kit:
  captcha:
    hcaptcha-secret: ${HCAPTCHA_SECRET}
    recaptcha-secret: ${RECAPTCHA_SECRET}
    recaptcha-score-threshold: ${RECAPTCHA_THRESHOLD}
  cdn:
    aliyun-domain: "33.unijzlsx.com"
    aliyun-key: ${CDN_AUTH_KEY}
sentry:
  dsn: ${SENTRY_SDN}
  traces-sample-rate: 1.0