kit:
  captcha:
    hcaptcha-secret: "0x0000000000000000000000000000000000000000"
    recaptcha-secret: "Test Key Not Found"
    recaptcha-score-threshold: 0.33
  cloud:
    aliyun-cdn-domain: "example.com"
    aliyun-cdn-key: "example"
    aliyun-access-key: "foo"
    aliyun-access-secret: "bar"
    aliyun-oss-bucket: "foo"
    aliyun-oss-endpoint: "bar"
  internal:
    access-key: "foo"
    access-secret: "bar"